{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a4b23885-1f39-4e45-819b-8b757f4ca9c1",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name '_name_' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[1], line 127\u001b[0m\n\u001b[0;32m    123\u001b[0m         \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m--- End of Report ---\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m    126\u001b[0m \u001b[38;5;66;03m# Execution block (Similar to your original run_advisor() call)\u001b[39;00m\n\u001b[1;32m--> 127\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m _name_ \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m_main_\u001b[39m\u001b[38;5;124m\"\u001b[39m:\n\u001b[0;32m    128\u001b[0m     advisor \u001b[38;5;241m=\u001b[39m BudgetAdvisor()\n\u001b[0;32m    129\u001b[0m     advisor\u001b[38;5;241m.\u001b[39mrun_advisor()\n",
      "\u001b[1;31mNameError\u001b[0m: name '_name_' is not defined"
     ]
    }
   ],
   "source": [
    "class BudgetAdvisor:\n",
    "    \"\"\"\n",
    "    A class to manage and advise on a college student's monthly budget.\n",
    "    Implements three functional modules: Input/Data Processing, Budget Calculation, and Financial Reporting.\n",
    "    \"\"\"\n",
    "\n",
    "    def _init_(self):\n",
    "        # Initialize key variables\n",
    "        self.income = 0.0\n",
    "        self.expenses = {}\n",
    "        self.total_expenses = 0.0\n",
    "        self.leftover = 0.0\n",
    "        self.savings_goal = {\"name\": \"\", \"amount\": 0.0}\n",
    "\n",
    "    # === Functional Module 1: Data Input & Processing ===\n",
    "    def _collect_financial_data(self):\n",
    "        \"\"\"Collects the user's monthly income and detailed expenses.\"\"\"\n",
    "        print(\"\\n--- 💰 Module 1: Data Input & Processing ---\")\n",
    "        \n",
    "        while True:\n",
    "            try:\n",
    "                self.income = float(input(\"Enter your total monthly income (job, allowance, etc.): $\"))\n",
    "                if self.income < 0:\n",
    "                    raise ValueError\n",
    "                break\n",
    "            except ValueError:\n",
    "                print(\"Invalid input. Please enter a positive number for income.\")\n",
    "\n",
    "        print(\"\\nEnter your monthly expenses:\")\n",
    "        # Use a dictionary to store expenses for a clear structure\n",
    "        expense_categories = {\n",
    "            \"Rent / Housing\": \"rent\",\n",
    "            \"Food / Groceries\": \"food\",\n",
    "            \"Transportation\": \"transportation\",\n",
    "            \"Utilities / Phone / Internet\": \"utilities\",\n",
    "            \"Entertainment / Eating Out\": \"entertainment\",\n",
    "            \"Other personal expenses\": \"others\"\n",
    "        }\n",
    "        \n",
    "        for name, key in expense_categories.items():\n",
    "            while True:\n",
    "                try:\n",
    "                    amount = float(input(f\"  {name}: $\"))\n",
    "                    if amount < 0:\n",
    "                        raise ValueError\n",
    "                    self.expenses[key] = amount\n",
    "                    break\n",
    "                except ValueError:\n",
    "                    print(\"Invalid input. Please enter a positive number for the expense.\")\n",
    "\n",
    "    # === Functional Module 2: Budget Calculation ===\n",
    "    def _calculate_budget(self):\n",
    "        \"\"\"Calculates total expenses and the leftover balance.\"\"\"\n",
    "        print(\"\\n--- 🧮 Module 2: Budget Calculation ---\")\n",
    "        \n",
    "        # Calculate total expenses\n",
    "        self.total_expenses = sum(self.expenses.values())\n",
    "        \n",
    "        # Calculate leftover money\n",
    "        self.leftover = self.income - self.total_expenses\n",
    "\n",
    "    # === Functional Module 3: Financial Reporting & Savings Advice ===\n",
    "    def _generate_report_and_advice(self):\n",
    "        \"\"\"Generates the budget summary, financial advice, and savings goal planner.\"\"\"\n",
    "        print(\"\\n--- 📊 Module 3: Financial Reporting & Advice ---\")\n",
    "        \n",
    "        # Budget Summary\n",
    "        print(\"\\n--- Monthly Budget Summary ---\")\n",
    "        print(f\"Total Income:     ${self.income:,.2f}\")\n",
    "        print(f\"Total Expenses:   ${self.total_expenses:,.2f}\")\n",
    "        print(f\"Money Left Over:  ${self.leftover:,.2f}\")\n",
    "\n",
    "        # Financial Advice\n",
    "        print(\"\\n--- Financial Advice ---\")\n",
    "\n",
    "        if self.leftover > 0:\n",
    "            print(\"✅ Great! You are spending less than you earn.\")\n",
    "\n",
    "            # Savings recommendation based on 50/30/20 rule (20% for savings/debt)\n",
    "            recommended_savings = self.income * 0.20\n",
    "            print(f\"- Based on the 20% rule, you should aim to save: ${recommended_savings:,.2f} per month.\")\n",
    "\n",
    "            if self.leftover < recommended_savings:\n",
    "                print(\"⚠ Warning: Your current leftover amount is less than the 20% savings target. Consider reducing entertainment or other flexible expenses.\")\n",
    "            else:\n",
    "                 print(\"Good job! You meet the 20% savings target.\")\n",
    "\n",
    "        elif self.leftover == 0:\n",
    "            print(\"⚠ Caution: You are breaking even. Try lowering some non-essential expenses to save money.\")\n",
    "        else:\n",
    "            print(\"❌ Warning: You are spending MORE than you earn! (Deficit: ${:.2f})\".format(abs(self.leftover)))\n",
    "            print(\"Action Needed: Try cutting down discretionary expenses or finding additional income sources (part-time job, tutoring, etc.).\")\n",
    "            \n",
    "        self._plan_savings_goal()\n",
    "        \n",
    "    def _plan_savings_goal(self):\n",
    "        \"\"\"Handles the savings goal planning feature.\"\"\"\n",
    "        print(\"\\n--- Savings Goal Planner ---\")\n",
    "        self.savings_goal[\"name\"] = input(\"Enter a savings goal (e.g., laptop, emergency fund): \")\n",
    "        \n",
    "        while True:\n",
    "            try:\n",
    "                self.savings_goal[\"amount\"] = float(input(\"Goal amount ($): \"))\n",
    "                if self.savings_goal[\"amount\"] < 0:\n",
    "                    raise ValueError\n",
    "                break\n",
    "            except ValueError:\n",
    "                print(\"Invalid input. Please enter a positive goal amount.\")\n",
    "\n",
    "        if self.leftover > 0:\n",
    "            months_needed = self.savings_goal[\"amount\"] / self.leftover\n",
    "            print(f\"At your current leftover amount (${self.leftover:,.2f} saved per month), you can reach your '{self.savings_goal['name']}' goal in about *{months_needed:.1f} months*.\")\n",
    "        else:\n",
    "            print(\"You currently cannot save toward your goal. Adjust spending or increase income first.\")\n",
    "\n",
    "    # === Main Execution Method ===\n",
    "    def run_advisor(self):\n",
    "        \"\"\"The main method to run the entire budget advisor program.\"\"\"\n",
    "        print(\"\\n--- Welcome to the College Student Budget & Savings Advisor ---\")\n",
    "        self._collect_financial_data()\n",
    "        self._calculate_budget()\n",
    "        self._generate_report_and_advice()\n",
    "        print(\"\\n--- End of Report ---\\n\")\n",
    "\n",
    "\n",
    "# Execution block (Similar to your original run_advisor() call)\n",
    "if _name_ == \"_main_\":\n",
    "    advisor = BudgetAdvisor()\n",
    "    advisor.run_advisor()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e0f56c76-62d8-4bf9-80c7-ff10969df652",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name '_name_' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[2], line 127\u001b[0m\n\u001b[0;32m    123\u001b[0m         \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m--- End of Report ---\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m    126\u001b[0m \u001b[38;5;66;03m# Execution block (Similar to your original run_advisor() call)\u001b[39;00m\n\u001b[1;32m--> 127\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m _name_ \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m_main_\u001b[39m\u001b[38;5;124m\"\u001b[39m:\n\u001b[0;32m    128\u001b[0m     advisor \u001b[38;5;241m=\u001b[39m BudgetAdvisor()\n\u001b[0;32m    129\u001b[0m     advisor\u001b[38;5;241m.\u001b[39mrun_advisor()\n",
      "\u001b[1;31mNameError\u001b[0m: name '_name_' is not defined"
     ]
    }
   ],
   "source": [
    "class BudgetAdvisor:\n",
    "    \"\"\"\n",
    "    A class to manage and advise on a college student's monthly budget.\n",
    "    Implements three functional modules: Input/Data Processing, Budget Calculation, and Financial Reporting.\n",
    "    \"\"\"\n",
    "\n",
    "    def _init_(self):\n",
    "        # Initialize key variables\n",
    "        self.income = 0.0\n",
    "        self.expenses = {}\n",
    "        self.total_expenses = 0.0\n",
    "        self.leftover = 0.0\n",
    "        self.savings_goal = {\"name\": \"\", \"amount\": 0.0}\n",
    "\n",
    "    # === Functional Module 1: Data Input & Processing ===\n",
    "    def _collect_financial_data(self):\n",
    "        \"\"\"Collects the user's monthly income and detailed expenses.\"\"\"\n",
    "        print(\"\\n--- 💰 Module 1: Data Input & Processing ---\")\n",
    "        \n",
    "        while True:\n",
    "            try:\n",
    "                self.income = float(input(\"Enter your total monthly income (job, allowance, etc.): $\"))\n",
    "                if self.income < 0:\n",
    "                    raise ValueError\n",
    "                break\n",
    "            except ValueError:\n",
    "                print(\"Invalid input. Please enter a positive number for income.\")\n",
    "\n",
    "        print(\"\\nEnter your monthly expenses:\")\n",
    "        # Use a dictionary to store expenses for a clear structure\n",
    "        expense_categories = {\n",
    "            \"Rent / Housing\": \"rent\",\n",
    "            \"Food / Groceries\": \"food\",\n",
    "            \"Transportation\": \"transportation\",\n",
    "            \"Utilities / Phone / Internet\": \"utilities\",\n",
    "            \"Entertainment / Eating Out\": \"entertainment\",\n",
    "            \"Other personal expenses\": \"others\"\n",
    "        }\n",
    "        \n",
    "        for name, key in expense_categories.items():\n",
    "            while True:\n",
    "                try:\n",
    "                    amount = float(input(f\"  {name}: $\"))\n",
    "                    if amount < 0:\n",
    "                        raise ValueError\n",
    "                    self.expenses[key] = amount\n",
    "                    break\n",
    "                except ValueError:\n",
    "                    print(\"Invalid input. Please enter a positive number for the expense.\")\n",
    "\n",
    "    # === Functional Module 2: Budget Calculation ===\n",
    "    def _calculate_budget(self):\n",
    "        \"\"\"Calculates total expenses and the leftover balance.\"\"\"\n",
    "        print(\"\\n--- 🧮 Module 2: Budget Calculation ---\")\n",
    "        \n",
    "        # Calculate total expenses\n",
    "        self.total_expenses = sum(self.expenses.values())\n",
    "        \n",
    "        # Calculate leftover money\n",
    "        self.leftover = self.income - self.total_expenses\n",
    "\n",
    "    # === Functional Module 3: Financial Reporting & Savings Advice ===\n",
    "    def _generate_report_and_advice(self):\n",
    "        \"\"\"Generates the budget summary, financial advice, and savings goal planner.\"\"\"\n",
    "        print(\"\\n--- 📊 Module 3: Financial Reporting & Advice ---\")\n",
    "        \n",
    "        # Budget Summary\n",
    "        print(\"\\n--- Monthly Budget Summary ---\")\n",
    "        print(f\"Total Income:     ${self.income:,.2f}\")\n",
    "        print(f\"Total Expenses:   ${self.total_expenses:,.2f}\")\n",
    "        print(f\"Money Left Over:  ${self.leftover:,.2f}\")\n",
    "\n",
    "        # Financial Advice\n",
    "        print(\"\\n--- Financial Advice ---\")\n",
    "\n",
    "        if self.leftover > 0:\n",
    "            print(\"✅ Great! You are spending less than you earn.\")\n",
    "\n",
    "            # Savings recommendation based on 50/30/20 rule (20% for savings/debt)\n",
    "            recommended_savings = self.income * 0.20\n",
    "            print(f\"- Based on the 20% rule, you should aim to save: ${recommended_savings:,.2f} per month.\")\n",
    "\n",
    "            if self.leftover < recommended_savings:\n",
    "                print(\"⚠ Warning: Your current leftover amount is less than the 20% savings target. Consider reducing entertainment or other flexible expenses.\")\n",
    "            else:\n",
    "                 print(\"Good job! You meet the 20% savings target.\")\n",
    "\n",
    "        elif self.leftover == 0:\n",
    "            print(\"⚠ Caution: You are breaking even. Try lowering some non-essential expenses to save money.\")\n",
    "        else:\n",
    "            print(\"❌ Warning: You are spending MORE than you earn! (Deficit: ${:.2f})\".format(abs(self.leftover)))\n",
    "            print(\"Action Needed: Try cutting down discretionary expenses or finding additional income sources (part-time job, tutoring, etc.).\")\n",
    "            \n",
    "        self._plan_savings_goal()\n",
    "        \n",
    "    def _plan_savings_goal(self):\n",
    "        \"\"\"Handles the savings goal planning feature.\"\"\"\n",
    "        print(\"\\n--- Savings Goal Planner ---\")\n",
    "        self.savings_goal[\"name\"] = input(\"Enter a savings goal (e.g., laptop, emergency fund): \")\n",
    "        \n",
    "        while True:\n",
    "            try:\n",
    "                self.savings_goal[\"amount\"] = float(input(\"Goal amount ($): \"))\n",
    "                if self.savings_goal[\"amount\"] < 0:\n",
    "                    raise ValueError\n",
    "                break\n",
    "            except ValueError:\n",
    "                print(\"Invalid input. Please enter a positive goal amount.\")\n",
    "\n",
    "        if self.leftover > 0:\n",
    "            months_needed = self.savings_goal[\"amount\"] / self.leftover\n",
    "            print(f\"At your current leftover amount (${self.leftover:,.2f} saved per month), you can reach your '{self.savings_goal['name']}' goal in about *{months_needed:.1f} months*.\")\n",
    "        else:\n",
    "            print(\"You currently cannot save toward your goal. Adjust spending or increase income first.\")\n",
    "\n",
    "    # === Main Execution Method ===\n",
    "    def run_advisor(self):\n",
    "        \"\"\"The main method to run the entire budget advisor program.\"\"\"\n",
    "        print(\"\\n--- Welcome to the College Student Budget & Savings Advisor ---\")\n",
    "        self._collect_financial_data()\n",
    "        self._calculate_budget()\n",
    "        self._generate_report_and_advice()\n",
    "        print(\"\\n--- End of Report ---\\n\")\n",
    "\n",
    "\n",
    "# Execution block (Similar to your original run_advisor() call)\n",
    "if _name_ == \"_main_\":\n",
    "    advisor = BudgetAdvisor()\n",
    "    advisor.run_advisor()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1cb2521c-4529-4a63-846a-4db0aa086116",
   "metadata": {},
   "source": [
    "## class BudgetAdvisor:\n",
    "    \"\"\"\n",
    "    A class to manage and advise on a college student's monthly budget.\n",
    "    Implements three functional modules: Input/Data Processing, Budget Calculation, and Financial Reporting.\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        # FIX: Changed _init_ to __init__ (double underscores)\n",
    "        self.income = 0.0\n",
    "        self.expenses = {}\n",
    "        self.total_expenses = 0.0\n",
    "        self.leftover = 0.0\n",
    "        self.savings_goal = {\"name\": \"\", \"amount\": 0.0}\n",
    "\n",
    "    # === Functional Module 1: Data Input & Processing ===\n",
    "    def _collect_financial_data(self):\n",
    "        \"\"\"Collects the user's monthly income and detailed expenses.\"\"\"\n",
    "        print(\"\\n--- 💰 Module 1: Data Input & Processing ---\")\n",
    "        \n",
    "        while True:\n",
    "            try:\n",
    "                self.income = float(input(\"Enter your total monthly income (job, allowance, etc.): $\"))\n",
    "                if self.income < 0:\n",
    "                    raise ValueError\n",
    "                break\n",
    "            except ValueError:\n",
    "                print(\"Invalid input. Please enter a positive number for income.\")\n",
    "\n",
    "        print(\"\\nEnter your monthly expenses:\")\n",
    "        expense_categories = {\n",
    "            \"Rent / Housing\": \"rent\",\n",
    "            \"Food / Groceries\": \"food\",\n",
    "            \"Transportation\": \"transportation\",\n",
    "            \"Utilities / Phone / Internet\": \"utilities\",\n",
    "            \"Entertainment / Eating Out\": \"entertainment\",\n",
    "            \"Other personal expenses\": \"others\"\n",
    "        }\n",
    "        \n",
    "        for name, key in expense_categories.items():\n",
    "            while True:\n",
    "                try:\n",
    "                    amount = float(input(f\"  {name}: $\"))\n",
    "                    if amount < 0:\n",
    "                        raise ValueError\n",
    "                    self.expenses[key] = amount\n",
    "                    break\n",
    "                except ValueError:\n",
    "                    print(\"Invalid input. Please enter a positive number for the expense.\")\n",
    "\n",
    "    # === Functional Module 2: Budget Calculation ===\n",
    "    def _calculate_budget(self):\n",
    "        \"\"\"Calculates total expenses and the leftover balance.\"\"\"\n",
    "        print(\"\\n--- 🧮 Module 2: Budget Calculation ---\")\n",
    "        \n",
    "        self.total_expenses = sum(self.expenses.values())\n",
    "        self.leftover = self.income - self.total_expenses\n",
    "\n",
    "    # === Functional Module 3: Financial Reporting & Savings Advice ===\n",
    "    def _generate_report_and_advice(self):\n",
    "        \"\"\"Generates the budget summary, financial advice, and savings goal planner.\"\"\"\n",
    "        print(\"\\n--- 📊 Module 3: Financial Reporting & Advice ---\")\n",
    "        \n",
    "        # Budget Summary\n",
    "        print(\"\\n--- Monthly Budget Summary ---\")\n",
    "        print(f\"Total Income:     ${self.income:,.2f}\")\n",
    "        print(f\"Total Expenses:   ${self.total_expenses:,.2f}\")\n",
    "        print(f\"Money Left Over:  ${self.leftover:,.2f}\")\n",
    "\n",
    "        # Financial Advice\n",
    "        print(\"\\n--- Financial Advice ---\")\n",
    "\n",
    "        if self.leftover > 0:\n",
    "            print(\"✅ Great! You are spending less than you earn.\")\n",
    "\n",
    "            # Savings recommendation based on 50/30/20 rule\n",
    "            recommended_savings = self.income * 0.20\n",
    "            print(f\"- Based on the 20% rule, you should aim to save: ${recommended_savings:,.2f} per month.\")\n",
    "\n",
    "            if self.leftover < recommended_savings:\n",
    "                print(\"⚠ Warning: Your current leftover amount is less than the 20% savings target.\")\n",
    "            else:\n",
    "                 print(\"Good job! You meet the 20% savings target.\")\n",
    "\n",
    "        elif self.leftover == 0:\n",
    "            print(\"⚠ Caution: You are breaking even. Try lowering some non-essential expenses.\")\n",
    "        else:\n",
    "            print(\"❌ Warning: You are spending MORE than you earn! (Deficit: ${:.2f})\".format(abs(self.leftover)))\n",
    "            print(\"Action Needed: Try cutting down discretionary expenses or finding additional income.\")\n",
    "            \n",
    "        self._plan_savings_goal()\n",
    "        \n",
    "    def _plan_savings_goal(self):\n",
    "        \"\"\"Handles the savings goal planning feature.\"\"\"\n",
    "        print(\"\\n--- Savings Goal Planner ---\")\n",
    "        self.savings_goal[\"name\"] = input(\"Enter a savings goal (e.g., laptop, emergency fund): \")\n",
    "        \n",
    "        while True:\n",
    "            try:\n",
    "                self.savings_goal[\"amount\"] = float(input(\"Goal amount ($): \"))\n",
    "                if self.savings_goal[\"amount\"] < 0:\n",
    "                    raise ValueError\n",
    "                break\n",
    "            except ValueError:\n",
    "                print(\"Invalid input. Please enter a positive goal amount.\")\n",
    "\n",
    "        if self.leftover > 0:\n",
    "            # Calculation using LaTeX context for clarity in thought\n",
    "            # Time = Goal / MonthlySavings\n",
    "            months_needed = self.savings_goal[\"amount\"] / self.leftover\n",
    "            print(f\"At your current leftover amount (${self.leftover:,.2f}/mo), you can reach your '{self.savings_goal['name']}' goal in about *{months_needed:.1f} months*.\")\n",
    "        else:\n",
    "            print(\"You currently cannot save toward your goal because you have no leftover funds.\")\n",
    "\n",
    "    # === Main Execution Method ===\n",
    "    def run_advisor(self):\n",
    "        print(\"\\n--- Welcome to the College Student Budget & Savings Advisor ---\")\n",
    "        self._collect_financial_data()\n",
    "        self._calculate_budget()\n",
    "        self._generate_report_and_advice()\n",
    "        print(\"\\n--- End of Report ---\\n\")\n",
    "\n",
    "\n",
    "# Execution block\n",
    "if __name__ == \"__main__\":\n",
    "\n",
    "    advisor = BudgetAdvisor()\n",
    "    advisor.run_advisor()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "c878a5f5-22a0-4bd5-af15-014ecd783412",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "--- Welcome to the College Student Budget & Savings Advisor ---\n",
      "\n",
      "--- 💰 Module 1: Data Input & Processing ---\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter your total monthly income (job, allowance, etc.): $ 12000\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Enter your monthly expenses:\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "  Rent / Housing: $ 3000\n",
      "  Food / Groceries: $ 5000\n",
      "  Transportation: $ 300\n",
      "  Utilities / Phone / Internet: $ 22\n",
      "  Entertainment / Eating Out: $ 100\n",
      "  Other personal expenses: $ 325\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "--- 🧮 Module 2: Budget Calculation ---\n",
      "\n",
      "--- 📊 Module 3: Financial Reporting & Advice ---\n",
      "\n",
      "--- Monthly Budget Summary ---\n",
      "Total Income:     $12,000.00\n",
      "Total Expenses:   $8,747.00\n",
      "Money Left Over:  $3,253.00\n",
      "\n",
      "--- Financial Advice ---\n",
      "✅ Great! You are spending less than you earn.\n",
      "- Based on the 20% rule, you should aim to save: $2,400.00 per month.\n",
      "Good job! You meet the 20% savings target.\n",
      "\n",
      "--- Savings Goal Planner ---\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter a savings goal (e.g., laptop, emergency fund):  1000\n",
      "Goal amount ($):  900\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "At your current leftover amount ($3,253.00/mo), you can reach your '1000' goal in about *0.3 months*.\n",
      "\n",
      "--- End of Report ---\n",
      "\n"
     ]
    }
   ],
   "source": [
    "class BudgetAdvisor:\n",
    "    \"\"\"\n",
    "    A class to manage and advise on a college student's monthly budget.\n",
    "    Implements three functional modules: Input/Data Processing, Budget Calculation, and Financial Reporting.\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        # FIX: Changed _init_ to __init__ (double underscores)\n",
    "        self.income = 0.0\n",
    "        self.expenses = {}\n",
    "        self.total_expenses = 0.0\n",
    "        self.leftover = 0.0\n",
    "        self.savings_goal = {\"name\": \"\", \"amount\": 0.0}\n",
    "\n",
    "    # === Functional Module 1: Data Input & Processing ===\n",
    "    def _collect_financial_data(self):\n",
    "        \"\"\"Collects the user's monthly income and detailed expenses.\"\"\"\n",
    "        print(\"\\n--- 💰 Module 1: Data Input & Processing ---\")\n",
    "        \n",
    "        while True:\n",
    "            try:\n",
    "                self.income = float(input(\"Enter your total monthly income (job, allowance, etc.): $\"))\n",
    "                if self.income < 0:\n",
    "                    raise ValueError\n",
    "                break\n",
    "            except ValueError:\n",
    "                print(\"Invalid input. Please enter a positive number for income.\")\n",
    "\n",
    "        print(\"\\nEnter your monthly expenses:\")\n",
    "        expense_categories = {\n",
    "            \"Rent / Housing\": \"rent\",\n",
    "            \"Food / Groceries\": \"food\",\n",
    "            \"Transportation\": \"transportation\",\n",
    "            \"Utilities / Phone / Internet\": \"utilities\",\n",
    "            \"Entertainment / Eating Out\": \"entertainment\",\n",
    "            \"Other personal expenses\": \"others\"\n",
    "        }\n",
    "        \n",
    "        for name, key in expense_categories.items():\n",
    "            while True:\n",
    "                try:\n",
    "                    amount = float(input(f\"  {name}: $\"))\n",
    "                    if amount < 0:\n",
    "                        raise ValueError\n",
    "                    self.expenses[key] = amount\n",
    "                    break\n",
    "                except ValueError:\n",
    "                    print(\"Invalid input. Please enter a positive number for the expense.\")\n",
    "\n",
    "    # === Functional Module 2: Budget Calculation ===\n",
    "    def _calculate_budget(self):\n",
    "        \"\"\"Calculates total expenses and the leftover balance.\"\"\"\n",
    "        print(\"\\n--- 🧮 Module 2: Budget Calculation ---\")\n",
    "        \n",
    "        self.total_expenses = sum(self.expenses.values())\n",
    "        self.leftover = self.income - self.total_expenses\n",
    "\n",
    "    # === Functional Module 3: Financial Reporting & Savings Advice ===\n",
    "    def _generate_report_and_advice(self):\n",
    "        \"\"\"Generates the budget summary, financial advice, and savings goal planner.\"\"\"\n",
    "        print(\"\\n--- 📊 Module 3: Financial Reporting & Advice ---\")\n",
    "        \n",
    "        # Budget Summary\n",
    "        print(\"\\n--- Monthly Budget Summary ---\")\n",
    "        print(f\"Total Income:     ${self.income:,.2f}\")\n",
    "        print(f\"Total Expenses:   ${self.total_expenses:,.2f}\")\n",
    "        print(f\"Money Left Over:  ${self.leftover:,.2f}\")\n",
    "\n",
    "        # Financial Advice\n",
    "        print(\"\\n--- Financial Advice ---\")\n",
    "\n",
    "        if self.leftover > 0:\n",
    "            print(\"✅ Great! You are spending less than you earn.\")\n",
    "\n",
    "            # Savings recommendation based on 50/30/20 rule\n",
    "            recommended_savings = self.income * 0.20\n",
    "            print(f\"- Based on the 20% rule, you should aim to save: ${recommended_savings:,.2f} per month.\")\n",
    "\n",
    "            if self.leftover < recommended_savings:\n",
    "                print(\"⚠ Warning: Your current leftover amount is less than the 20% savings target.\")\n",
    "            else:\n",
    "                 print(\"Good job! You meet the 20% savings target.\")\n",
    "\n",
    "        elif self.leftover == 0:\n",
    "            print(\"⚠ Caution: You are breaking even. Try lowering some non-essential expenses.\")\n",
    "        else:\n",
    "            print(\"❌ Warning: You are spending MORE than you earn! (Deficit: ${:.2f})\".format(abs(self.leftover)))\n",
    "            print(\"Action Needed: Try cutting down discretionary expenses or finding additional income.\")\n",
    "            \n",
    "        self._plan_savings_goal()\n",
    "        \n",
    "    def _plan_savings_goal(self):\n",
    "        \"\"\"Handles the savings goal planning feature.\"\"\"\n",
    "        print(\"\\n--- Savings Goal Planner ---\")\n",
    "        self.savings_goal[\"name\"] = input(\"Enter a savings goal (e.g., laptop, emergency fund): \")\n",
    "        \n",
    "        while True:\n",
    "            try:\n",
    "                self.savings_goal[\"amount\"] = float(input(\"Goal amount ($): \"))\n",
    "                if self.savings_goal[\"amount\"] < 0:\n",
    "                    raise ValueError\n",
    "                break\n",
    "            except ValueError:\n",
    "                print(\"Invalid input. Please enter a positive goal amount.\")\n",
    "\n",
    "        if self.leftover > 0:\n",
    "            # Calculation using LaTeX context for clarity in thought\n",
    "            # Time = Goal / MonthlySavings\n",
    "            months_needed = self.savings_goal[\"amount\"] / self.leftover\n",
    "            print(f\"At your current leftover amount (${self.leftover:,.2f}/mo), you can reach your '{self.savings_goal['name']}' goal in about *{months_needed:.1f} months*.\")\n",
    "        else:\n",
    "            print(\"You currently cannot save toward your goal because you have no leftover funds.\")\n",
    "\n",
    "    # === Main Execution Method ===\n",
    "    def run_advisor(self):\n",
    "        print(\"\\n--- Welcome to the College Student Budget & Savings Advisor ---\")\n",
    "        self._collect_financial_data()\n",
    "        self._calculate_budget()\n",
    "        self._generate_report_and_advice()\n",
    "        print(\"\\n--- End of Report ---\\n\")\n",
    "\n",
    "\n",
    "# Execution block\n",
    "if __name__ == \"__main__\":\n",
    "    # FIX: Changed _name_ and _main_ to __name__ and __main__\n",
    "    advisor = BudgetAdvisor()\n",
    "    advisor.run_advisor()\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f58cff64-039a-4c51-9ada-e0c9f72c9bf6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
